Global:
  model_name: PP-OCRv5_server_rec
  use_gpu: true
  epoch_num: 100  # Достаточно для одного слова
  log_smooth_window: 1
  print_batch_step: 5
  save_model_dir: ./output/
  save_epoch_step: 20
  eval_batch_step: [0, 10]  # Чаще смотрим прогресс
  cal_metric_during_train: true
  pretrained_model: ./text/typed_text/pretrain_models/PP-OCRv5_server_rec_pretrained.pdparams
  character_dict_path: ./text/debug/dict.txt
  max_text_length: 10
  use_space_char: false

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001  # Оптимально для быстрого старта
  regularizer:
    name: L2
    factor: 0.00001

Architecture:
  # Без изменений - оставляем PP-OCRv5_server_rec
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.5
    pretrained: false
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: false
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/debug
    label_file_list:
      - ./text/debug/train_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [ 3, 32, 320 ]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ]
  loader:
    shuffle: true
    batch_size_per_card: 32  # УВЕЛИЧИТЬ! A40 потянет
    drop_last: false
    num_workers: 4  # Увеличить для скорости
    use_shared_memory: true

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/debug
    label_file_list:
      - ./text/debug/val_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - SVTRRecResizeImg:
          image_shape: [ 3, 32, 320 ]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ]
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 4
    use_shared_memory: true