Global:
  model_name: PP-OCRv5_server_rec
  use_gpu: true
  epoch_num: 150
  log_smooth_window: 1
  print_batch_step: 10
  save_model_dir: ./output/
  save_inference_dir: ./output_inference/
  save_epoch_step: 10
  eval_batch_step: [0, 1]
  cal_metric_during_train: true
  pretrained_model: ./text/typed_text/pretrain_models/PP-OCRv5_server_rec_pretrained.pdparams
  checkpoints:
  character_dict_path: ./text/debug/dict.txt
  max_text_length: 10
  use_space_char: false
  infer_mode: false
  save_res_path: ./output/debug_predicts.txt
  use_visualdl: false

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: L2
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.5
    pretrained: false
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: false
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/debug
    label_file_list:
      - ./text/debug/train_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ]
  loader:
    shuffle: true
    batch_size_per_card: 2
    drop_last: false
    num_workers: 0
    use_shared_memory: false

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/debug
    label_file_list:
      - ./text/debug/val_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - SVTRRecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ]
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 2
    num_workers: 0
    use_shared_memory: false