Global:
  model_name: PP-OCRv5_server_rec
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/
  save_inference_dir: ./output_inference_aze/
  save_epoch_step: 20
  eval_batch_step: [0, 500]
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints:
  character_dict_path: ./text/typed_text/pure_azerbaijani_cyrillic_dataset/dict.txt
  max_text_length: 15  # Увеличил для длинных слов
  use_space_char: false
  infer_mode: false
  save_res_path: ./output/aze_predicts.txt
  use_visualdl: true

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
    schedulers:
      - name: CosineAnnealingLR
        T_max: 300
        eta_min: 0.00001
  regularizer:
    name: L2
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
    pretrained: false
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 512  # Увеличил для сложных символов
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/typed_text/pure_azerbaijani_cyrillic_dataset
    label_file_list:
      - ./text/typed_text/pure_azerbaijani_cyrillic_dataset/train_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 400]  # Увеличил размер для лучшего качества
          padding: true
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: true
    batch_size_per_card: 256
    drop_last: true
    num_workers: 16
    use_shared_memory: true

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/typed_text/pure_azerbaijani_cyrillic_dataset
    label_file_list:
      - ./text/typed_text/pure_azerbaijani_cyrillic_dataset/val_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - SVTRRecResizeImg:
          image_shape: [3, 48, 400]
          padding: true
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 16
    use_shared_memory: true