Global:
  model: PP-OCRv5_server_rec
  mode: train
  dataset_dir: "./text/typed_text/pure_azerbaijani_cyrillic_dataset"
  device: gpu:0
  output: "output_az"

Train:
  epochs_iters: 100
  batch_size: 64
  learning_rate: 0.001
  pretrain_weight_path: "./text/typed_text/pretrain_models/PP-OCRv5_server_rec_pretrained.pdparams"
  resume_path: null
  log_interval: 50
  eval_interval: 1
  save_interval: 5

Evaluate:
  weight_path: "output_az/best_accuracy/best_accuracy.pdparams"
  log_interval: 1

Export:
  weight_path: "output_az/best_accuracy/best_accuracy.pdparams"

Custom:
  character_dict_path: "./text/typed_text/pure_azerbaijani_cyrillic_dataset/dict.txt"
  use_space_char: true
  max_text_length: 40
