Global:
  use_gpu: true
  gpu_mem: 15000
  save_model_dir: ./output/
  pretrained_model: ./text/typed_text/pretrain_models/cyrillic_PP-OCRv3_rec_train.tar
  character_dict_path: ./text/typed_text/az_ru_dict.txt
  max_text_length: 25
  use_space_char: true
  epoch_num: 100

Architecture:
  model_type: rec
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

Optimizer:
  name: Adam
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0.00001

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/typed_text/
    label_file_list:
      - ./text/typed_text/train_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: true
    batch_size_per_card: 128
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./text/typed_text/
    label_file_list:
      - ./text/typed_text/val_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: false
    batch_size_per_card: 128
    num_workers: 4